import { Ingredient, Recipe } from './types';

export const DEFAULT_INGREDIENTS: Ingredient[] = [
  // หมวดเนื้อสัตว์และซีฟู้ด (Meats & Seafood)
  { id: 'pork_minced', name: 'หมูสับ', name_en: 'Minced Pork', category: 'meat', icon: '🥩', cal_per_100g: 240 },
  { id: 'pork_sliced', name: 'เนื้อหมู/หมูชิ้น', name_en: 'Sliced Pork', category: 'meat', icon: '🥩', cal_per_100g: 210 },
  { id: 'crispy_pork', name: 'หมูกรอบ', name_en: 'Crispy Pork Belly', category: 'meat', icon: '🥓', cal_per_100g: 385 },
  { id: 'bacon', name: 'เบคอน', name_en: 'Bacon', category: 'meat', icon: '🥓', cal_per_100g: 400 },
  { id: 'chicken_breast', name: 'อกไก่', name_en: 'Chicken Breast', category: 'meat', icon: '🍗', cal_per_100g: 120 },
  { id: 'chicken_thigh', name: 'สะโพก/น่องไก่', name_en: 'Chicken Thigh', category: 'meat', icon: '🍗', cal_per_100g: 190 },
  { id: 'shrimp', name: 'กุ้งสด', name_en: 'Fresh Shrimp', category: 'meat', icon: '🦐', cal_per_100g: 85 },
  { id: 'squid', name: 'ปลาหมึกสด', name_en: 'Fresh Squid', category: 'meat', icon: '🦑', cal_per_100g: 92 },
  { id: 'canned_fish', name: 'ปลากระป๋อง', name_en: 'Canned Fish', category: 'meat', icon: '🐟', cal_per_100g: 130 },
  { id: 'sausage', name: 'ไส้กรอก', name_en: 'Sausage', category: 'meat', icon: '🌭', cal_per_100g: 280 },
  { id: 'crab_stick', name: 'ปูอัด', name_en: 'Crab Stick', category: 'meat', icon: '🦀', cal_per_100g: 110 },
  { id: 'egg_tofu', name: 'เต้าหู้ไข่', name_en: 'Egg Tofu', category: 'meat', icon: '🧈', cal_per_100g: 75 },
  { id: 'firm_tofu', name: 'เต้าหู้ขาว/แข็ง', name_en: 'White Tofu', category: 'meat', icon: '🧈', cal_per_100g: 80 },

  // หมวดผักและเห็ด (Vegetables & Mushrooms)
  { id: 'chinese_cabbage', name: 'ผักกาดขาว', name_en: 'Chinese Cabbage', category: 'veggie', icon: '🥬', cal_per_100g: 16 },
  { id: 'cabbage', name: 'กะหล่ำปลี', name_en: 'Cabbage', category: 'veggie', icon: '🥬', cal_per_100g: 25 },
  { id: 'holy_basil', name: 'ใบกะเพรา', name_en: 'Holy Basil', category: 'veggie', icon: '🌿', cal_per_100g: 22 },
  { id: 'morning_glory', name: 'ผักบุ้ง', name_en: 'Morning Glory', category: 'veggie', icon: '🌱', cal_per_100g: 19 },
  { id: 'chinese_kale', name: 'คะน้า', name_en: 'Chinese Kale', category: 'veggie', icon: '🥬', cal_per_100g: 28 },
  { id: 'carrot', name: 'แครอท', name_en: 'Carrot', category: 'veggie', icon: '🥕', cal_per_100g: 41 },
  { id: 'onion', name: 'หอมใหญ่', name_en: 'Onion', category: 'veggie', icon: '🧅', cal_per_100g: 40 },
  { id: 'shallot', name: 'หอมแดง', name_en: 'Shallot', category: 'veggie', icon: '🧅', cal_per_100g: 45 },
  { id: 'tomato', name: 'มะเขือเทศ', name_en: 'Tomato', category: 'veggie', icon: '🍅', cal_per_100g: 18 },
  { id: 'cucumber', name: 'แตงกวา', name_en: 'Cucumber', category: 'veggie', icon: '🥒', cal_per_100g: 15 },
  { id: 'broccoli', name: 'บรอกโคลี', name_en: 'Broccoli', category: 'veggie', icon: '🥦', cal_per_100g: 34 },
  { id: 'baby_corn', name: 'ข้าวโพดอ่อน', name_en: 'Baby Corn', category: 'veggie', icon: '🌽', cal_per_100g: 30 },
  { id: 'enoki_mushroom', name: 'เห็ดเข็มทอง', name_en: 'Enoki Mushroom', category: 'veggie', icon: '🍄', cal_per_100g: 37 },
  { id: 'shimeji_mushroom', name: 'เห็ดชิเมจิ', name_en: 'Shimeji Mushroom', category: 'veggie', icon: '🍄', cal_per_100g: 32 },
  { id: 'spring_onion', name: 'ต้นหอม-ผักชี', name_en: 'Spring Onion & Cilantro', category: 'veggie', icon: '🌿', cal_per_100g: 25 },
  { id: 'chili', name: 'พริกขี้หนู', name_en: 'Chili', category: 'veggie', icon: '🌶️', is_staple: true, cal_per_100g: 40 },
  { id: 'garlic', name: 'กระเทียม', name_en: 'Garlic', category: 'veggie', icon: '🧄', is_staple: true, cal_per_100g: 149 },
  { id: 'lime', name: 'มะนาว', name_en: 'Lime', category: 'veggie', icon: '🍋', is_staple: true, cal_per_100g: 29 },
  { id: 'ginger', name: 'ขิง', name_en: 'Ginger', category: 'veggie', icon: '🫚', cal_per_100g: 80 },
  { id: 'tom_yum_herbs', name: 'ข่า ตะไคร้ ใบมะกรูด', name_en: 'Tom Yum Herbs', category: 'veggie', icon: '🌿', cal_per_100g: 35 },

  // หมวดเครื่องปรุงและของติดตู้เย็น (Seasonings & Sauces)
  { id: 'egg', name: 'ไข่ไก่', name_en: 'Egg', category: 'staple', icon: '🥚', is_staple: true, cal_per_100g: 143 },
  { id: 'fish_sauce', name: 'น้ำปลา', name_en: 'Fish Sauce', category: 'seasoning', icon: '🍾', is_staple: true, cal_per_100g: 35 },
  { id: 'oyster_sauce', name: 'ซอสหอยนางรม', name_en: 'Oyster Sauce', category: 'seasoning', icon: '🫙', is_staple: true, cal_per_100g: 51 },
  { id: 'soy_sauce', name: 'ซีอิ๊วขาว', name_en: 'Light Soy Sauce', category: 'seasoning', icon: '🍶', is_staple: true, cal_per_100g: 50 },
  { id: 'dark_soy_sauce', name: 'ซีอิ๊วดำ', name_en: 'Dark Soy Sauce', category: 'seasoning', icon: '🍶', is_staple: true, cal_per_100g: 75 },
  { id: 'sugar', name: 'น้ำตาลทราย', name_en: 'Sugar', category: 'seasoning', icon: '🧂', is_staple: true, cal_per_100g: 387 },
  { id: 'cooking_oil', name: 'น้ำมันพืช', name_en: 'Cooking Oil', category: 'seasoning', icon: '🫗', is_staple: true, cal_per_100g: 884 },
  { id: 'bouillon_cube', name: 'ซุปก้อน/รสดี', name_en: 'Soup Bouillon', category: 'seasoning', icon: '🧊', is_staple: true, cal_per_100g: 150 },
  { id: 'pepper', name: 'พริกไทยป่น', name_en: 'Ground Pepper', category: 'seasoning', icon: '🧂', is_staple: true, cal_per_100g: 250 },
  { id: 'chili_paste', name: 'น้ำพริกเผา', name_en: 'Thai Chili Paste', category: 'seasoning', icon: '🌶️', cal_per_100g: 320 },
  { id: 'green_curry_paste', name: 'พริกแกงเขียวหวาน', name_en: 'Green Curry Paste', category: 'seasoning', icon: '🍛', cal_per_100g: 140 },
  { id: 'coconut_milk', name: 'กะทิ', name_en: 'Coconut Milk', category: 'seasoning', icon: '🥥', cal_per_100g: 230 },
  { id: 'suki_sauce', name: 'น้ำจิ้มสุกี้', name_en: 'Suki Sauce', category: 'seasoning', icon: '🥣', cal_per_100g: 110 },
  { id: 'butter', name: 'เนยสด', name_en: 'Butter', category: 'seasoning', icon: '🧈', cal_per_100g: 717 },
  { id: 'cheese', name: 'ชีส', name_en: 'Cheese', category: 'seasoning', icon: '🧀', cal_per_100g: 402 },

  // หมวดแป้ง ข้าว เส้น (Carbs & Staples)
  { id: 'steamed_rice', name: 'ข้าวสวย', name_en: 'Cooked Rice', category: 'carb', icon: '🍚', is_staple: true, cal_per_100g: 130 },
  { id: 'wide_rice_noodles', name: 'เส้นใหญ่', name_en: 'Wide Rice Noodles', category: 'carb', icon: '🍜', cal_per_100g: 160 },
  { id: 'rice_vermicelli', name: 'เส้นเล็ก/เส้นหมี่', name_en: 'Rice Noodles', category: 'carb', icon: '🍜', cal_per_100g: 140 },
  { id: 'glass_noodles', name: 'วุ้นเส้น', name_en: 'Glass Noodles', category: 'carb', icon: '🥢', cal_per_100g: 120 },
  { id: 'instant_noodles', name: 'บะหมี่กึ่งสำเร็จรูป', name_en: 'Instant Noodles', category: 'carb', icon: '🍜', cal_per_100g: 380 },
  { id: 'bread', name: 'ขนมปัง', name_en: 'Bread', category: 'carb', icon: '🍞', cal_per_100g: 265 },
];

export const DEFAULT_RECIPES: Recipe[] = [
  {
    id: 'cabbage_soup_pork',
    title: 'แกงจืดผักกาดขาวหมูสับ',
    description: 'เมนูซดน้ำซุปร้อนๆ หวานธรรมชาติจากผักกาดขาวและเนื้อหมูสับนุ่มๆ ทำง่ายมาก แคลอรีต่ำ สบายท้อง',
    category: 'soup',
    cooking_time_minutes: 15,
    difficulty: 'ง่าย',
    calories: 180,
    protein_g: 18,
    carbs_g: 8,
    fat_g: 7,
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำแกงจืดผักกาดขาวหมูสับ',
    tags: ['ทำง่าย', 'แคลอรีต่ำ', 'เมนูซดน้ำ', 'เด็กทานได้'],
    steps: [
      'หมักหมูสับด้วยซีอิ๊วขาวและพริกไทยเล็กน้อย ปั้นเป็นก้อนกลมพอดีคำ',
      'ต้มน้ำสะอาดในหม้อให้เดือด ใส่ซุปก้อนหรือกระเทียมบุบลงไป',
      'พอน้ำเดือดพล่าน ใส่หมูสับปั้นก้อนลงไปต้มจนสุกและลอยขึ้นมาบนผิวน้ำ',
      'ใส่ผักกาดขาวหั่นชิ้นลงไป ปรุงรสด้วยซีอิ๊วขาว รอให้ผักสลด ปิดไฟ โรยพริกไทยและต้นหอมพร้อมเสิร์ฟ'
    ],
    ingredients: [
      { ingredient_id: 'pork_minced', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'chinese_cabbage', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'garlic', amount: '2 กลีบ', is_optional: true },
      { ingredient_id: 'soy_sauce', amount: '1 ช้อนโต๊ะ', is_optional: true },
      { ingredient_id: 'bouillon_cube', amount: '1/2 ก้อน', is_optional: true },
      { ingredient_id: 'pepper', amount: 'ตามชอบ', is_optional: true },
    ],
  },
  {
    id: 'pad_krapao_pork',
    title: 'ผัดกะเพราหมูสับไข่ดาว',
    description: 'เมนูยอดนิยมอันดับหนึ่ง รสจัดจ้าน เผ็ดร้อนกลิ่นใบกะเพราสด ทานคู่กับไข่ดาวกรอบไข่แดงเยิ้มๆ',
    category: 'stir_fry',
    cooking_time_minutes: 10,
    difficulty: 'ง่าย',
    calories: 550,
    protein_g: 28,
    carbs_g: 45,
    fat_g: 26,
    image_url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำผัดกะเพราหมูสับไข่ดาว',
    tags: ['เมนูด่วน', 'เผ็ดแซ่บ', 'ยอดนิยมอันดับ 1'],
    steps: [
      'โขลกพริกขี้หนูกับกระเทียมพอหยาบๆ',
      'ตั้งกระทะใส่น้ำมัน นำพริกกระเทียมลงไปผัดจนส่งกลิ่นหอมฉุนเตะจมูก',
      'ใส่หมูสับลงไปผัด ยีเนื้อให้กระจายตัว ปรุงรสด้วยซอสหอยนางรม ซีอิ๊วขาว น้ำปลา และน้ำตาลตัดรสเล็กน้อย',
      'เร่งไฟแรง ใส่ใบกะเพราลงไป ผัดเร็วๆ 10 วินาที ปิดไฟ ตักราดข้าวสวยเสิร์ฟพร้อมไข่ดาว'
    ],
    ingredients: [
      { ingredient_id: 'pork_minced', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'holy_basil', amount: '1 กำมือ', is_optional: false },
      { ingredient_id: 'chili', amount: '5 เม็ด', is_optional: false },
      { ingredient_id: 'garlic', amount: '3 กลีบ', is_optional: false },
      { ingredient_id: 'egg', amount: '1 ฟอง (ทอดไข่ดาว)', is_optional: false },
      { ingredient_id: 'steamed_rice', amount: '1 จาน', is_optional: true },
      { ingredient_id: 'oyster_sauce', amount: '1 ช้อนโต๊ะ', is_optional: true },
      { ingredient_id: 'fish_sauce', amount: '1 ช้อนโต๊ะ', is_optional: true },
    ],
  },
  {
    id: 'pad_krapao_squid',
    title: 'ผัดกะเพราปลาหมึกไข่ดาว',
    description: 'ปลาหมึกสดเนื้อเด้งกรุบกรอบ ผัดพริกกระเทียมและใบกะเพราเข้มข้น รสชาติเผ็ดร้อนสะใจ',
    category: 'stir_fry',
    cooking_time_minutes: 10,
    difficulty: 'ง่าย',
    calories: 460,
    protein_g: 32,
    carbs_g: 44,
    fat_g: 16,
    image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำผัดกะเพราปลาหมึก',
    tags: ['ซีฟู้ด', 'เมนูด่วน', 'เผ็ดแซ่บ'],
    steps: [
      'ล้างปลาหมึก บั้งเป็นตารางแล้วหั่นชิ้นพอดีคำ ลวกในน้ำเดือด 10 วินาทีแล้วตักขึ้นสะเด็ดน้ำ',
      'ผัดพริกและกระเทียมตำหยาบในกระทะจนหอมฟุ้ง',
      'เร่งไฟแรง ใส่ปลาหมึกลงไป ปรุงรสด้วยซอสหอยนางรม น้ำปลา น้ำตาลทราย',
      'ใส่ใบกะเพรา ผัดคลุกเคล้าเร็วๆ 10 วินาที ตักเสิร์ฟพร้อมข้าวสวยร้อนๆ และไข่ดาว'
    ],
    ingredients: [
      { ingredient_id: 'squid', amount: '180 กรัม', is_optional: false },
      { ingredient_id: 'holy_basil', amount: '1 กำมือ', is_optional: false },
      { ingredient_id: 'chili', amount: '5 เม็ด', is_optional: false },
      { ingredient_id: 'garlic', amount: '3 กลีบ', is_optional: false },
      { ingredient_id: 'egg', amount: '1 ฟอง', is_optional: true },
      { ingredient_id: 'oyster_sauce', amount: '1 ช้อนโต๊ะ', is_optional: true },
    ],
  },
  {
    id: 'pork_fried_rice',
    title: 'ข้าวผัดหมูใส่ไข่',
    description: 'ข้าวผัดหอมกลิ่นกระทะ ข้าวเรียงเม็ดสวย เคล้าเนื้อหมูและไข่ไก่หอมมัน อิ่มอร่อยง่ายๆ ได้ทั้งครอบครัว',
    category: 'rice',
    cooking_time_minutes: 12,
    difficulty: 'ง่าย',
    calories: 480,
    protein_g: 22,
    carbs_g: 58,
    fat_g: 16,
    image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำข้าวผัดหมูใส่ไข่',
    tags: ['จานเดียวอิ่ม', 'ทำง่าย', 'เมนูเร่งด่วน'],
    steps: [
      'ตั้งกระทะใส่น้ำมัน เจียวกระเทียมสับให้หอม ใส่หมูชิ้นลงไปผัดพอสุก',
      'ตอกไข่ไก่ลงไป ยีให้กระจายทั่วกระทะ พอไข่เริ่มสุกเซ็ตตัว',
      'ใส่ข้าวสวยลงไปคลุกเคล้า ปรุงรสด้วยซีอิ๊วขาว น้ำตาล และพริกไทยป่น',
      'ผัดด้วยไฟแรงให้เข้ากันทั่ว โรยต้นหอมซอย ตักใส่จานเสิร์ฟพร้อมมะนาวและแตงกวา'
    ],
    ingredients: [
      { ingredient_id: 'pork_sliced', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'egg', amount: '1-2 ฟอง', is_optional: false },
      { ingredient_id: 'steamed_rice', amount: '1 ถ้วย', is_optional: false },
      { ingredient_id: 'garlic', amount: '2 กลีบ', is_optional: true },
      { ingredient_id: 'spring_onion', amount: '1 ต้น', is_optional: true },
      { ingredient_id: 'soy_sauce', amount: '1 ช้อนโต๊ะ', is_optional: true },
    ],
  },
  {
    id: 'shrimp_fried_rice',
    title: 'ข้าวผัดกุ้งสดเนื้อเด้ง',
    description: 'ข้าวผัดสีทองหอมกลิ่นไข่และกระทะ คลุกเคล้ากุ้งสดตัวโตเนื้อหวานเด้ง โรยต้นหอมซอยและพริกไทย',
    category: 'rice',
    cooking_time_minutes: 10,
    difficulty: 'ง่าย',
    calories: 420,
    protein_g: 26,
    carbs_g: 54,
    fat_g: 12,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำข้าวผัดกุ้ง',
    tags: ['ซีฟู้ด', 'จานเดียวอิ่ม', 'ทำง่าย'],
    steps: [
      'แกะเปลือกกุ้ง ผ่าหลังดึงเส้นดำออก ล้างให้สะอาด',
      'เจียวกระเทียมในน้ำมันร้อน ใส่กุ้งลงไปผัดพอสะดุ้งสุก 80% ตักพักไว้',
      'ตอกไข่ลงในกระทะเดิม ยีให้พอเซ็ตตัว ใส่ข้าวสวยลงผัดด้วยไฟแรง',
      'ใส่กุ้งกลับลงไป ปรุงรสด้วยซีอิ๊วขาว น้ำตาล โรยต้นหอม ตักเสิร์ฟพร้อมมะนาว'
    ],
    ingredients: [
      { ingredient_id: 'shrimp', amount: '5-6 ตัว', is_optional: false },
      { ingredient_id: 'egg', amount: '1-2 ฟอง', is_optional: false },
      { ingredient_id: 'steamed_rice', amount: '1 ถ้วย', is_optional: false },
      { ingredient_id: 'garlic', amount: '2 กลีบ', is_optional: true },
      { ingredient_id: 'spring_onion', amount: '1 ต้น', is_optional: true },
    ],
  },
  {
    id: 'minced_pork_omelette',
    title: 'ไข่เจียวหมูสับทรงเครื่อง',
    description: 'ไข่เจียวสีเหลืองทอง ฟูกรอบนอกนุ่มใน หอมอร่อยกลมกล่อม ทำได้ง่ายมากใน 5 นาที ทานกับข้าวสวยร้อนๆ',
    category: 'fried',
    cooking_time_minutes: 7,
    difficulty: 'ง่าย',
    calories: 340,
    protein_g: 19,
    carbs_g: 4,
    fat_g: 27,
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำไข่เจียวหมูสับฟูกรอบ',
    tags: ['เมนูด่วนสุดๆ', 'ทำง่ายมาก', 'อร่อยคู่ข้าวสวย'],
    steps: [
      'ตอกไข่ใส่ชาม ใส่หมูสับ ปรุงรสด้วยน้ำปลาและซีอิ๊วขาวเล็กน้อย',
      'ตีไข่และหมูสับด้วยส้อมให้เข้ากันจนเกิดฟองฟูละเอียด',
      'ตั้งกระทะใส่น้ำมัน รอน้ำมันร้อนจัดจนมีควันจางๆ เทไข่ลงไปจากที่สูง',
      'ทอดจนด้านล่างเหลืองกรอบ พลิกกลับด้าน ทอดต่อจนสุกหอมทั้งสองด้าน ตักสะเด็ดน้ำมันเสิร์ฟ'
    ],
    ingredients: [
      { ingredient_id: 'egg', amount: '2-3 ฟอง', is_optional: false },
      { ingredient_id: 'pork_minced', amount: '80 กรัม', is_optional: false },
      { ingredient_id: 'fish_sauce', amount: '1 ช้อนโต๊ะ', is_optional: true },
      { ingredient_id: 'cooking_oil', amount: 'สำหรับทอด', is_optional: true },
    ],
  },
  {
    id: 'creamy_scrambled_egg_shrimp',
    title: 'ข้าวไข่ขยี้กุ้งสดพริกกระเทียม',
    description: 'ไข่ขยี้เนื้อเนียนนุ่มเยิ้มๆ คลุกเคล้ากุ้งเด้งหวาน ท็อปด้วยพริกซอยและกระเทียมเจียวหอมๆ ราดข้าวสวยร้อนๆ',
    category: 'rice',
    cooking_time_minutes: 8,
    difficulty: 'ง่าย',
    calories: 390,
    protein_g: 24,
    carbs_g: 45,
    fat_g: 14,
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำข้าวไข่ขยี้กุ้ง',
    tags: ['เมนูฮิตโซเชียล', 'ทำง่ายมาก', 'ไข่นุ่มเยิ้ม'],
    steps: [
      'ลวกกุ้งสดในน้ำเดือดพอสุก พักไว้',
      'ตอกไข่ 2 ฟอง ปรุงน้ำปลาปลายช้อน ตีพอแตก',
      'ตั้งกระทะไฟอ่อน ใส่น้ำมันบางๆ เทไข่ลงไป ใช้ตะหลิวดันไข่จากขอบเข้าหาตรงกลางเบาๆ จนเป็นริ้วเยิ้มๆ',
      'วางกุ้งลงไปบนไข่ โรยพริกขี้หนูซอยและต้นหอม ปิดไฟ ตักโปะบนข้าวสวยร้อนๆ'
    ],
    ingredients: [
      { ingredient_id: 'egg', amount: '2 ฟอง', is_optional: false },
      { ingredient_id: 'shrimp', amount: '4-5 ตัว', is_optional: false },
      { ingredient_id: 'steamed_rice', amount: '1 จาน', is_optional: false },
      { ingredient_id: 'chili', amount: '2 เม็ด', is_optional: true },
      { ingredient_id: 'fish_sauce', amount: '1 ช้อนชา', is_optional: true },
    ],
  },
  {
    id: 'cabbage_fishsauce_bacon',
    title: 'กะหล่ำปลีทอดน้ำปลาเบคอนกรอบ',
    description: 'กะหล่ำปลีฉ่ำหวานกรอบ ผัดไฟแรงเคล้าน้ำปลาหอมกลิ่นกระทะไหม้ พร้อมเบคอนทอดกรอบเค็มมัน',
    category: 'stir_fry',
    cooking_time_minutes: 8,
    difficulty: 'ง่าย',
    calories: 280,
    protein_g: 14,
    carbs_g: 12,
    fat_g: 20,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำกะหล่ำปลีทอดน้ำปลาเบคอน',
    tags: ['เมนูร้านอาหารดัง', 'กรอบหอม', 'ทำง่าย'],
    steps: [
      'ฉีกกะหล่ำปลีเป็นชิ้นใหญ่ ล้างน้ำสะอาด พักให้แห้งสนิท',
      'ทอดเบคอนในกระทะจนกรอบ ตักเบคอนขึ้น เหลือน้ำมันไว้ในกระทะเล็กน้อย',
      'เร่งไฟแรงจนกระทะร้อนจัด ใส่กะหล่ำปลีลงไป อย่าเพิ่งคน รอ 15 วินาทีให้ผักโดนความร้อน',
      'ราดน้ำปลาดีลงข้างขอบกระทะให้เกิดเสียงฉ่าและกลิ่นหอมไหม้ คลุกเร็วๆ 15 วินาที โรยเบคอนกรอบตักเสิร์ฟ'
    ],
    ingredients: [
      { ingredient_id: 'cabbage', amount: '200 กรัม', is_optional: false },
      { ingredient_id: 'bacon', amount: '60 กรัม', is_optional: false },
      { ingredient_id: 'garlic', amount: '2 กลีบ', is_optional: true },
      { ingredient_id: 'fish_sauce', amount: '1.5 ช้อนโต๊ะ', is_optional: false },
    ],
  },
  {
    id: 'kale_crispy_pork',
    title: 'คะน้าหมูกรอบผัดน้ำมันหอย',
    description: 'ยอดคะน้าสดกรอบ ผัดไฟลุกเคล้าซอสหอยนางรมกลมกล่อม ทานคู่หมูกรอบหนังพองกรุบฟินสุดๆ',
    category: 'stir_fry',
    cooking_time_minutes: 10,
    difficulty: 'ง่าย',
    calories: 490,
    protein_g: 22,
    carbs_g: 14,
    fat_g: 38,
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำคะน้าหมูกรอบ',
    tags: ['ยอดนิยมอันดับต้น', 'หมูกรอบฟิน', 'รสเข้มข้น'],
    steps: [
      'หั่นคะน้าแยกก้านและใบ วางพริกกระเทียมบุบ ซอสหอยนางรม และน้ำตาลบนผักคะน้า',
      'ตั้งกระทะใส่น้ำมัน รอจนกระทะร้อนจัดควันขึ้น',
      'เทคะน้าและเครื่องปรุงทั้งหมดลงไปผัดเร็วๆ 15 วินาที',
      'ใส่หมูกรอบหั่นชิ้นลงไปคลุกเคล้า 10 วินาที ปิดไฟทันทีเพื่อรักษาความกรอบของหนังหมู'
    ],
    ingredients: [
      { ingredient_id: 'crispy_pork', amount: '120 กรัม', is_optional: false },
      { ingredient_id: 'chinese_kale', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'garlic', amount: '3 กลีบ', is_optional: false },
      { ingredient_id: 'chili', amount: '4 เม็ด', is_optional: false },
      { ingredient_id: 'oyster_sauce', amount: '1.5 ช้อนโต๊ะ', is_optional: true },
    ],
  },
  {
    id: 'crispy_pork_chili_salt',
    title: 'หมูกรอบคั่วพริกเกลือ',
    description: 'หมูกรอบเนื้อแน่นหนังกรอบ คั่วแห้งๆ เคล้ากระเทียมสับเจียวเหลืองกรอบและพริกขี้หนูซอย รสเด็ดจัดจ้าน',
    category: 'stir_fry',
    cooking_time_minutes: 10,
    difficulty: 'ง่าย',
    calories: 520,
    protein_g: 24,
    carbs_g: 10,
    fat_g: 42,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำหมูกรอบคั่วพริกเกลือ',
    tags: ['กับแกล้มชั้นยอด', 'กรอบสะท้าน', 'รสเด็ด'],
    steps: [
      'เจียวกระเทียมสับและพริกขี้หนูซอยในกระทะด้วยไฟกลางจนเริ่มเหลืองหอม',
      'ใส่หมูกรอบที่หั่นชิ้นลงไปคั่วด้วยไฟกลางค่อนแรง',
      'ปรุงรสด้วยเกลือป่น น้ำตาลทราย และพริกไทยป่น คั่วให้เครื่องปรุงเกาะชิ้นหมูกรอบ',
      'โรยต้นหอมซอย คั่วเร็วๆ อีก 10 วินาที ตักขึ้นเสิร์ฟ'
    ],
    ingredients: [
      { ingredient_id: 'crispy_pork', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'garlic', amount: '4 กลีบ', is_optional: false },
      { ingredient_id: 'chili', amount: '5 เม็ด', is_optional: false },
      { ingredient_id: 'spring_onion', amount: '1 ต้น', is_optional: true },
      { ingredient_id: 'pepper', amount: '1/2 ช้อนชา', is_optional: true },
    ],
  },
  {
    id: 'tom_yum_goong',
    title: 'ต้มยำกุ้งน้ำใสสมุนไพรสด',
    description: 'ต้มยำรสแซ่บจี๊ดจ๊าด หอมสมุนไพร ข่า ตะไคร้ ใบมะกรูด กุ้งสดหวานฉ่ำ เปรี้ยวเค็มเผ็ดลงตัว',
    category: 'soup',
    cooking_time_minutes: 15,
    difficulty: 'ง่าย',
    calories: 190,
    protein_g: 25,
    carbs_g: 8,
    fat_g: 4,
    image_url: 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำต้มยำกุ้งน้ำใส',
    tags: ['เมนูประจำชาติ', 'รสแซ่บ', 'สมุนไพรแน่น'],
    steps: [
      'ต้มน้ำให้เดือด ใส่ข่า ตะไคร้ ใบมะกรูด และหอมแดงลงไปต้มจนส่งกลิ่นหอม',
      'ใส่เห็ด (เห็ดฟางหรือชิเมจิ) และมะเขือเทศลงไปต้มจนสุก',
      'ใส่กุ้งสดลงไป อย่าคน รอจนกุ้งเปลี่ยนเป็นสีส้มสุกพอดี ปิดไฟเตา',
      'ปรุงรสด้วยน้ำปลา พริกขี้หนูบุบ และบีบน้ำมะนาวสด โรยผักชีพร้อมเสิร์ฟ'
    ],
    ingredients: [
      { ingredient_id: 'shrimp', amount: '6-8 ตัว', is_optional: false },
      { ingredient_id: 'tom_yum_herbs', amount: '1 ชุด', is_optional: false },
      { ingredient_id: 'chili', amount: '6 เม็ด', is_optional: false },
      { ingredient_id: 'lime', amount: '1.5 ลูก', is_optional: false },
      { ingredient_id: 'fish_sauce', amount: '2 ช้อนโต๊ะ', is_optional: false },
      { ingredient_id: 'tomato', amount: '1 ลูก', is_optional: true },
    ],
  },
  {
    id: 'green_curry_chicken',
    title: 'แกงเขียวหวานไก่ใส่กะทิสด',
    description: 'แกงไทยรสกลมกล่อม หอมพริกแกงเขียวหวานและกะทิมันเข้มข้น เนื้อไก่นุ่มชุ่มฉ่ำ ทานคู่ข้าวสวยหรือขนมจีน',
    category: 'soup',
    cooking_time_minutes: 20,
    difficulty: 'ปานกลาง',
    calories: 420,
    protein_g: 28,
    carbs_g: 12,
    fat_g: 28,
    image_url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำแกงเขียวหวานไก่',
    tags: ['แกงไทยโบราณ', 'หอมกะทิ', 'อร่อยกลมกล่อม'],
    steps: [
      'เคี่ยวกะทิส่วนหัวในหม้อจนแตกมัน ใส่พริกแกงเขียวหวานลงผัดจนส่งกลิ่นหอมฟุ้ง',
      'ใส่เนื้อไก่ลงไปผัดจนตึงและสุก เติมกะทิส่วนหางลงไปต้มจนเดือด',
      'ปรุงรสด้วยน้ำปลาและน้ำตาลปี๊บ/น้ำตาลทราย ชิมรสให้หวานมันเค็มพอดี',
      'ใส่ใบมะกรูด พริกชี้ฟ้า และใบโหระพา/กะเพรา ปิดไฟตักเสิร์ฟ'
    ],
    ingredients: [
      { ingredient_id: 'chicken_thigh', amount: '200 กรัม', is_optional: false },
      { ingredient_id: 'green_curry_paste', amount: '2 ช้อนโต๊ะ', is_optional: false },
      { ingredient_id: 'coconut_milk', amount: '250 มล.', is_optional: false },
      { ingredient_id: 'fish_sauce', amount: '1.5 ช้อนโต๊ะ', is_optional: true },
      { ingredient_id: 'sugar', amount: '1 ช้อนชา', is_optional: true },
    ],
  },
  {
    id: 'enoki_pork_stirfry',
    title: 'เห็ดเข็มทองผัดหมูสับน้ำมันหอย',
    description: 'เห็ดเข็มทองเนื้อสัมผัสกรุบกรอบ ผัดเคล้าหมูสับปรุงรสและซอสหอยนางรมหอมกระเทียม ทำง่ายใน 7 นาที',
    category: 'stir_fry',
    cooking_time_minutes: 7,
    difficulty: 'ง่าย',
    calories: 220,
    protein_g: 17,
    carbs_g: 10,
    fat_g: 12,
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำเห็ดเข็มทองผัดหมูสับ',
    tags: ['ทำง่ายมาก', 'เห็ดกรุบกรอบ', 'แคลต่ำ'],
    steps: [
      'ตัดโคนเห็ดเข็มทอง ฉีกเป็นช่อเล็กๆ ล้างให้สะอาด พักสะเด็ดน้ำ',
      'เจียวกระเทียมสับในน้ำมันร้อน ใส่หมูสับลงไปผัดจนสุก',
      'เร่งไฟแรง ใส่เห็ดเข็มทองลงไป ปรุงด้วยซอสหอยนางรม ซีอิ๊วขาว',
      'ผัดเร็วๆ 30 วินาทีจนเห็ดสลด โรยพริกไทยและต้นหอม ปิดไฟตักใส่จาน'
    ],
    ingredients: [
      { ingredient_id: 'enoki_mushroom', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'pork_minced', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'garlic', amount: '2 กลีบ', is_optional: false },
      { ingredient_id: 'oyster_sauce', amount: '1.5 ช้อนโต๊ะ', is_optional: true },
    ],
  },
  {
    id: 'tofu_pork_soup',
    title: 'แกงจืดเต้าหู้ไข่หมูสับผักกาด',
    description: 'แกงจืดซุปใสหวานละมุน ชิ้นเต้าหู้ไข่เนื้อเนียนนุ่ม หมูสับปรุงรส และผักกาดขาว สบายท้องสุดๆ',
    category: 'soup',
    cooking_time_minutes: 15,
    difficulty: 'ง่าย',
    calories: 210,
    protein_g: 20,
    carbs_g: 9,
    fat_g: 9,
    image_url: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำแกงจืดเต้าหู้ไข่หมูสับ',
    tags: ['เด็กทานได้', 'เมนูซดน้ำ', 'ทำง่าย', 'โปรตีนดี'],
    steps: [
      'หั่นเต้าหู้ไข่เป็นท่อนหนาประมาณ 1.5 ซม. พักไว้เบาๆ มือ',
      'ต้มน้ำเดือดใส่ซุปก้อน ใส่หมูสับปั้นก้อนลงไปต้มจนสุกและลอยขึ้น',
      'ใส่ผักกาดขาวลงไปต้มจนผักนิ่ม ปรุงรสด้วยซีอิ๊วขาว',
      'ค่อยๆ ใส่เต้าหู้ไข่ลงไป ต้มต่ออีก 1 นาทีเบาๆ ระวังเต้าหู้เละ ปิดไฟโรยพริกไทย'
    ],
    ingredients: [
      { ingredient_id: 'egg_tofu', amount: '1 หลอด', is_optional: false },
      { ingredient_id: 'pork_minced', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'chinese_cabbage', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'bouillon_cube', amount: '1/2 ก้อน', is_optional: true },
    ],
  },
  {
    id: 'suki_soup_chicken',
    title: 'สุกี้น้ำอกไก่รวมมิตร',
    description: 'สุกี้น้ำร้อนๆ อุดมด้วยผักกาดขาว ผักบุ้ง วุ้นเส้น และอกไก่นุ่ม ซดคล่องคอ สุขภาพดี เหมาะกับคนลดน้ำหนัก',
    category: 'soup',
    cooking_time_minutes: 15,
    difficulty: 'ง่าย',
    calories: 260,
    protein_g: 27,
    carbs_g: 28,
    fat_g: 3,
    image_url: 'https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำสุกี้น้ำอกไก่',
    tags: ['อาหารคลีน', 'เมนูซดน้ำ', 'ผักเยอะ', 'แคลต่ำ'],
    steps: [
      'ต้มน้ำซุปให้เดือด ใส่ซุปก้อนหรือเกลือเล็กน้อย',
      'ใส่อกไก่หั่นชิ้นลงต้มจนสุกขาว',
      'ใส่ผักกาดขาว ผักบุ้ง และวุ้นเส้นที่แช่น้ำแล้วลงไป',
      'ตอกไข่ไก่ใส่ชาม ตีพอแตกแล้วเทวนลงในหม้อซุป คนเบาๆ ให้เป็นริ้ว ปิดไฟ เสิร์ฟคู่น้ำจิ้มสุกี้'
    ],
    ingredients: [
      { ingredient_id: 'chicken_breast', amount: '120 กรัม', is_optional: false },
      { ingredient_id: 'chinese_cabbage', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'morning_glory', amount: '50 กรัม', is_optional: true },
      { ingredient_id: 'glass_noodles', amount: '40 กรัม', is_optional: false },
      { ingredient_id: 'egg', amount: '1 ฟอง', is_optional: false },
      { ingredient_id: 'suki_sauce', amount: '2 ช้อนโต๊ะ', is_optional: true },
    ],
  },
  {
    id: 'clean_chicken_salad',
    title: 'สลัดอกไก่ไข่ต้มผักสดเพื่อสุขภาพ',
    description: 'อกไก่ต้มฉีกเป็นเส้น ทานคู่กับไข่ต้มยางมะตูม ผักสลัด มะเขือเทศ และแตงกวา โปรตีนสูง ไขมันต่ำสุดๆ',
    category: 'clean',
    cooking_time_minutes: 12,
    difficulty: 'ง่าย',
    calories: 240,
    protein_g: 36,
    carbs_g: 8,
    fat_g: 6,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำสลัดอกไก่คลีน',
    tags: ['อาหารคลีน', 'โปรตีนสูงมาก', 'ลดน้ำหนัก'],
    steps: [
      'ต้มอกไก่และไข่ไก่ในน้ำเดือดจนสุก ตักแช่น้ำเย็น ปอกเปลือกไข่แล้วผ่าครึ่ง ส่วนอกไก่ฉีกเป็นเส้น',
      'ล้างผักสด มะเขือเทศ และแตงกวา หั่นชิ้นจัดเรียงลงในจาน',
      'วางอกไก่ฉีกและไข่ต้มลงบนผัก',
      'โรยพริกไทยดำ ราดน้ำสลัดใสหรือบีบมะนาวสดตามชอบ'
    ],
    ingredients: [
      { ingredient_id: 'chicken_breast', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'egg', amount: '1 ฟอง', is_optional: false },
      { ingredient_id: 'tomato', amount: '1 ลูก', is_optional: false },
      { ingredient_id: 'cucumber', amount: '1 ลูก', is_optional: false },
    ],
  },
  {
    id: 'pad_see_ew_pork',
    title: 'ผัดซีอิ๊วหมูเส้นใหญ่',
    description: 'เส้นใหญ่นุ่มเหนียว ผัดไฟแรงเคลือบซีอิ๊วดำหอมกลิ่นกระทะ หมูนุ่มและผักคะน้ากรอบอร่อย',
    category: 'noodle',
    cooking_time_minutes: 12,
    difficulty: 'ง่าย',
    calories: 520,
    protein_g: 25,
    carbs_g: 62,
    fat_g: 18,
    image_url: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำผัดซีอิ๊วหมูเส้นใหญ่',
    tags: ['เมนูเส้นยอดฮิต', 'จานเดียวอิ่ม', 'ทำง่าย'],
    steps: [
      'ผัดกระเทียมกับหมูชิ้นในน้ำมันร้อนจนสุกพอดี',
      'ตอกไข่ไก่ลงไป ยีให้สุกเป็นชิ้นสวยงาม',
      'ใส่เส้นใหญ่ ปรุงรสด้วยซีอิ๊วดำ ซอสหอยนางรม น้ำปลา น้ำตาล',
      'ใส่ผักคะน้า เร่งไฟแรง ผัดเร็วๆ จนเส้นเกรียมหอม ปิดไฟโรยพริกไทย'
    ],
    ingredients: [
      { ingredient_id: 'wide_rice_noodles', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'pork_sliced', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'chinese_kale', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'egg', amount: '1 ฟอง', is_optional: false },
      { ingredient_id: 'dark_soy_sauce', amount: '1 ช้อนโต๊ะ', is_optional: true },
      { ingredient_id: 'garlic', amount: '2 กลีบ', is_optional: true },
    ],
  },
  {
    id: 'pad_thai_shrimp',
    title: 'ผัดไทยกุ้งสดหอมกระทะ',
    description: 'ก๋วยเตี๋ยวผัดไทยเส้นเหนียวนุ่ม เคลือบซอสมะขามเปียกครบรส เคล้ากุ้งสดตัวโต ไข่ไก่ และเต้าหู้แข็ง',
    category: 'noodle',
    cooking_time_minutes: 15,
    difficulty: 'ปานกลาง',
    calories: 540,
    protein_g: 28,
    carbs_g: 68,
    fat_g: 18,
    image_url: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำผัดไทยกุ้งสด',
    tags: ['อาหารประจำชาติ', 'ยอดนิยมระดับโลก', 'กลมกล่อม'],
    steps: [
      'เจียวกระเทียม หอมแดง และเต้าหู้หั่นเต๋าจนเหลืองหอม ใส่กุ้งลงผัดพอสุก ตักกุ้งพักไว้',
      'ใส่เส้นและน้ำเปล่าเล็กน้อย ผัดจนเส้นสุกนุ่ม ปรุงรสด้วยน้ำตาล น้ำปลา มะนาว',
      'เกลี่ยเส้นไปข้างกระทะ ตอกไข่ลงไป ยีให้สุกแล้วตลบเส้นมาทับ',
      'ใส่กุ้งกลับลงไป ผัดให้เข้ากัน ตักเสิร์ฟพร้อมมะนาวและถั่วงอกสด'
    ],
    ingredients: [
      { ingredient_id: 'shrimp', amount: '5 ตัว', is_optional: false },
      { ingredient_id: 'rice_vermicelli', amount: '120 กรัม', is_optional: false },
      { ingredient_id: 'egg', amount: '1 ฟอง', is_optional: false },
      { ingredient_id: 'firm_tofu', amount: '50 กรัม', is_optional: true },
      { ingredient_id: 'lime', amount: '1 ลูก', is_optional: true },
    ],
  },
  {
    id: 'pad_morning_glory_pork',
    title: 'ผัดผักบุ้งไฟแดงหมูสับ',
    description: 'ผักบุ้งกรอบเขียวสด รสเข้มข้นจัดจ้านด้วยพริกกระเทียมและเต้าเจี้ยว เคล้าหมูสับหอมๆ',
    category: 'stir_fry',
    cooking_time_minutes: 8,
    difficulty: 'ง่าย',
    calories: 230,
    protein_g: 17,
    carbs_g: 9,
    fat_g: 13,
    image_url: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำผัดผักบุ้งไฟแดง',
    tags: ['เมนูด่วน', 'ผักเยอะ', 'รสจัดจ้าน'],
    steps: [
      'ล้างผักบุ้ง ตัดท่อน วางพริกกระเทียมบุบ ซอสหอยนางรม และน้ำตาลบนยอดผักบุ้งเตรียมไว้',
      'ตั้งกระทะใส่น้ำมันและหมูสับ ผัดให้หมูสุกเกือบหมด',
      'เร่งไฟให้แรงสุดจนกระทะร้อนจัด เทผักบุ้งและเครื่องปรุงทั้งหมดลงไปพร้อมกัน',
      'ผัดพลิกกลับด้านเร็วๆ 15-20 วินาที ปิดไฟตักใส่จานทันที ผักจะกรอบสีเขียวสดสวย'
    ],
    ingredients: [
      { ingredient_id: 'morning_glory', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'pork_minced', amount: '80 กรัม', is_optional: false },
      { ingredient_id: 'garlic', amount: '3 กลีบ', is_optional: false },
      { ingredient_id: 'chili', amount: '4 เม็ด', is_optional: false },
      { ingredient_id: 'oyster_sauce', amount: '1.5 ช้อนโต๊ะ', is_optional: true },
    ],
  },
  {
    id: 'larb_pork',
    title: 'ลาบหมูรสแซ่บสมุนไพรข้าวคั่ว',
    description: 'หมูสับรวนสุกนุ่ม คลุกเคล้าพริกป่น ข้าวคั่วหอมฟุ้ง น้ำมะนาวสดแท้ และหอมแดง ซี้ดซ้าดถึงใจ',
    category: 'clean',
    cooking_time_minutes: 10,
    difficulty: 'ง่าย',
    calories: 220,
    protein_g: 26,
    carbs_g: 6,
    fat_g: 9,
    image_url: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำลาบหมู',
    tags: ['อีสานแซ่บ', 'แคลต่ำ', 'โปรตีนเน้นๆ'],
    steps: [
      'รวนหมูสับในหม้อใส่น้ำเปล่า 2 ช้อนโต๊ะ รวนจนหมูสุกดี ยกลงจากเตา',
      'ปรุงรสด้วยน้ำปลา น้ำมะนาว และพริกป่น คนให้เข้ากัน',
      'ใส่ข้าวคั่ว หอมแดงซอย และต้นหอมผักชีลงไป',
      'คลุกเคล้าเบาๆ ชิมรสเปรี้ยวเค็มเผ็ดตามชอบ ตักใส่จานทานคู่ผักสด'
    ],
    ingredients: [
      { ingredient_id: 'pork_minced', amount: '150 กรัม', is_optional: false },
      { ingredient_id: 'lime', amount: '1.5 ลูก', is_optional: false },
      { ingredient_id: 'fish_sauce', amount: '1.5 ช้อนโต๊ะ', is_optional: false },
      { ingredient_id: 'shallot', amount: '2 หัว', is_optional: true },
      { ingredient_id: 'spring_onion', amount: '1 ต้น', is_optional: true },
    ],
  },
  {
    id: 'spicy_canned_fish',
    title: 'ยำปลากระป๋องสมุนไพรสด',
    description: 'เมนูคู่หูเด็กหอและทุกบ้าน รสแซ่บจี๊ดจ๊าด หอมพริก มะนาว หอมแดง และต้นหอมผักชี ทำเสร็จใน 3 นาที',
    category: 'clean',
    cooking_time_minutes: 5,
    difficulty: 'ง่าย',
    calories: 190,
    protein_g: 21,
    carbs_g: 7,
    fat_g: 8,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำยำปลากระป๋อง',
    tags: ['เมนูด่วนสุดๆ', 'รสแซ่บ', 'ประหยัดงบ'],
    steps: [
      'เปิดปลากระป๋องเทใส่ชาม แยกเนื้อหรือยีพอหยาบตามชอบ',
      'ซอยพริกขี้หนู หอมใหญ่ และต้นหอมผักชีใส่ลงไป',
      'บีบน้ำมะนาว เหยาะน้ำปลาเล็กน้อย คนคลุกเคล้าให้เข้ากันชิมรสตามชอบ',
      'ตักเสิร์ฟคู่ข้าวสวยร้อนๆ หรือทานแกล้มผักสด'
    ],
    ingredients: [
      { ingredient_id: 'canned_fish', amount: '1 กระป๋อง', is_optional: false },
      { ingredient_id: 'chili', amount: '3-5 เม็ด', is_optional: false },
      { ingredient_id: 'lime', amount: '1 ลูก', is_optional: false },
      { ingredient_id: 'onion', amount: '1/4 หัว', is_optional: true },
      { ingredient_id: 'spring_onion', amount: '1 ต้น', is_optional: true },
    ],
  },
  {
    id: 'mama_krapao_pork',
    title: 'มาม่าผัดกะเพราหมูสับ',
    description: 'บะหมี่กึ่งสำเร็จรูปเหนียวนุ่ม ผัดคลุกเคล้าซอสกะเพราเข้มข้นรสเด็ด เผ็ดหอมใบกะเพราสุดฟิน',
    category: 'noodle',
    cooking_time_minutes: 10,
    difficulty: 'ง่าย',
    calories: 590,
    protein_g: 24,
    carbs_g: 68,
    fat_g: 22,
    image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80',
    video_url: 'https://www.youtube.com/results?search_query=วิธีทำมาม่าผัดกะเพรา',
    tags: ['เมนูด่วน', 'เด็กหอยอดฮิต', 'รสเด็ด'],
    steps: [
      'ลวกเส้นมาม่าในน้ำเดือดแค่พอนุ่มพอดี (อย่านานเกินไป) ตักสะเด็ดน้ำคลุกน้ำมันเล็กน้อย',
      'ผัดพริกกระเทียมและหมูสับในกระทะจนสุกหอม',
      'ใส่เส้นมาม่าลงไป ปรุงรสด้วยซอสหอยนางรม ซีอิ๊วขาว และผงปรุงรสมาม่าครึ่งซอง',
      'ใส่ใบกะเพรา ผัดไฟแรงคลุกเคล้าให้เข้ากันเร็วๆ ปิดไฟเสิร์ฟ'
    ],
    ingredients: [
      { ingredient_id: 'instant_noodles', amount: '1 ซอง', is_optional: false },
      { ingredient_id: 'pork_minced', amount: '100 กรัม', is_optional: false },
      { ingredient_id: 'holy_basil', amount: '1 กำมือ', is_optional: false },
      { ingredient_id: 'chili', amount: '4 เม็ด', is_optional: false },
      { ingredient_id: 'garlic', amount: '2 กลีบ', is_optional: false },
    ],
  }
];
